"""create table milestone

Revision ID: b70c13e2af02
Revises: 964b023b882b
Create Date: 2024-02-03 21:29:24.344099+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b70c13e2af02'
down_revision = '964b023b882b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('project_id', sa.INTEGER(), nullable=False, comment='プロジェクトID'),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False, comment='名称'),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True, comment='開始日'),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True, comment='終了日'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone')
    # ### end Alembic commands ###
